name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - name: Checkout the code    # Adds a step to checkout the repository code
      uses: actions/checkout@v2 
    - name: Build the application
      run: |
        docker build --target development --tag todo-app:dev .
    - name: Run the unit and integration tests
      working-directory: .
      run: | 
        docker build --target test --tag todo-app:test .
        docker run --env-file .env.test --mount type=bind,source="$(pwd)",target=/app/ todo-app:test todo_app_tests
    - name: Run the e2e tests
      working-directory: .
      run: | 
        docker build --target e2etest --tag todo-app:e2etest .
        docker run --env TRELLO_API_KEY=f0d5da5df98284c240a5a8a65a0b0e96 --env TRELLO_TOKEN=546b3a441384d0d83b195b85d8e58c9643542c3974a20100284bfe639db057ad --env TRELLO_BOARD_NAME=E2E_Test_Board --mount type=bind,source="$(pwd)",target=/app/ todo-app:e2etest todo_app_e2e_tests
      env:
        FLASK_APP: todo_app/app  # Flask server configuration.        