name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - name: Checkout the code    # Adds a step to checkout the repository code
      uses: actions/checkout@v2 
    - name: Build the application
      run: |
        docker build --target development --tag todo-app:dev .